My Demo Project-1/Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace GameNews.Models
{
    public class Contact
    {
        public int Id { get; set; }
        [MaxLength(1000)]
        [Required]
        public string Message { get; set; }

        [MaxLength(50)]
        [Required]
        public string Name { get; set; }
        public int? AppUserID { get; set; }

        public virtual AppUser AppUser { get; set; }
    }
}

My Demo Project-1/Areas/Management/Controllers/HomeController.cs
using GameNews.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameNews.Areas.Management.Controllers
{
    [Area("management")]
    [Authorize(Roles = "admin")]
    public class HomeController : Controller
    {
        readonly RoleManager<AppUserRole> _roleManager;
        readonly UserManager<AppUser> _userManager;
        public HomeController(RoleManager<AppUserRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;

        }

        public async Task< IActionResult> Index()
        {
            return View(_userManager.Users.ToList());
        }
        public async Task<IActionResult> DeleteRole(string id)
        {
           AppUserRole role = await _roleManager.FindByIdAsync(id);
           await _roleManager.DeleteAsync(role);
            return RedirectToAction("index");
        }
        public IActionResult Roles()
        {
            return View(_roleManager.Roles.ToList());
        }
        public IActionResult AddRole()
        {

            return View();
        }
        [HttpPost]
        public async Task< IActionResult> AddRole(RoleVM role)
        {
            var result = await _roleManager.CreateAsync(new AppUserRole { Name = role.Name });
            if (result.Succeeded)
            {
                return RedirectToAction("index");

            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("",item.Description);
                    
                }
                return View(role);
            }
            return View();
        }
        public async Task<IActionResult> RoleAssign(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            List<AppUserRole> roles = _roleManager.Roles.ToList();
            List<string> userRoles = await _userManager.GetRolesAsync(user) as List<string>;
            List<RoleAssignViewModel> assignRoles = new List<RoleAssignViewModel>();
            roles.ForEach(role => assignRoles.Add(new RoleAssignViewModel
            {
                HasAssign = userRoles.Contains(role.Name),
                RoleId = role.Id,
                RoleName = role.Name
            }));

            return View(assignRoles);
        }
        [HttpPost]
        public async Task<IActionResult> RoleAssign(List<RoleAssignViewModel> modellist,string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            foreach (RoleAssignViewModel role in modellist)
            {
                if (role.HasAssign)
                    await _userManager.AddToRoleAsync(user, role.RoleName);
                else
                    await _userManager.RemoveFromRoleAsync(user, role.RoleName);
            }
            return RedirectToAction("Index");
        }

    }
}

My Demo Project-1/Components/LastCommentsViewComponent.cs
using GameNews.Models;
using GameNews.RepositoryDesingPattern.Base;
using GameNews.RepositoryDesingPattern.Concrete;
using GameNews.RepositoryDesingPattern.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace GameNews.Components
{
    public class LastCommentsViewComponent:ViewComponent
    {
        readonly INewsDto _newsRepository;
        public LastCommentsViewComponent(INewsDto newRepository)
        {
           _newsRepository = newRepository;
        }
        
        public IViewComponentResult Invoke()
        {
            List<NewsVM> news=_newsRepository.GetNewsLastComments();
            return View(news);
        }
    }
}

My Demo Project-1/Components/SliderViewComponent.cs
using GameNews.Models;
using GameNews.RepositoryDesingPattern.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace GameNews.Components
{
    public class SliderViewComponent:ViewComponent
    {
        readonly INewsDto _newsDto;
        public SliderViewComponent(INewsDto newsDto)
        {
            _newsDto = newsDto;
        }

        public IViewComponentResult Invoke()
        {
            List<NewsVM> news = _newsDto.GetNewsSliderComponent();
            return View(news);
        }
    }
}

My Demo Project-1/Components/TopViewsViewComponent.cs
using GameNews.Models;
using GameNews.RepositoryDesingPattern.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace GameNews.Components
{
    public class TopViewsViewComponent:ViewComponent
    {
        readonly INewsDto _newsDto;
        public TopViewsViewComponent(INewsDto newsDto)
        {
            _newsDto = newsDto;
        }
        public IViewComponentResult Invoke()
        {
            List<NewsVM> news = _newsDto.GetNewsMostViewed();
            return View(news);
        }
    }
}

My Demo Project-1/Controllers/HomeController.cs
using GameNews.Models;
using GameNews.RepositoryDesingPattern.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameNews.Controllers
{

    public class HomeController : Controller
    {
        readonly INewsDto _news;
        readonly IRepositoryBase<Contact> _contactRepository;
        readonly UserManager<AppUser> _userManager;
        readonly CookieHelper _cookieHelper;
        public HomeController(INewsDto news, UserManager<AppUser> userManager,IRepositoryBase<Contact> contactrepository, CookieHelper cookieHelper)
        {
            _news = news;
            _userManager = userManager;
            _contactRepository = contactrepository;
            _cookieHelper = cookieHelper;
        }

        public  async Task<IActionResult> Index()
        {
            List<NewsVM> news = _news.GetNewsVMIndex();

            return View(news);
        }
        public IActionResult Contact()
        {
            
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Contact(Contact contact)
        {
            if (ModelState.IsValid)
            {
                if (User.Identity.IsAuthenticated)
                {
                    AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
                    contact.AppUserID = user.Id;
                    contact.Name = user.UserName;
                    _contactRepository.Add(contact);
                    return RedirectToAction("index");
                }
                _contactRepository.Add(contact);
                return RedirectToAction("index");
            }


            return View(contact);
        }
        public IActionResult Error()
        {
            return View();
        }
    }
}

My Demo Project-1/Views/Home/Contact.cshtml
@model Contact
@section signupscripts{
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}
    <section class="normal-breadcrumb set-bg" data-setbg="/img/normal-breadcrumb.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="normal__breadcrumb__text">
                        <h2>Contact</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="login__form">
                        <h3>Contact</h3>
                        <form asp-action="contact" asp-controller="home" method="post">
                            <span asp-validation-for="Name" style="color:white"></span>
                            <div class="form-outline">
                                <input type="text" placeholder="Name" class="form-control" asp-for="Name" id="textAreaExample1" rows="3"></input>
                            </div>
                            <br />
                            <span asp-validation-for="Message" style="color:white"></span>
                            <div class="form-outline">
                                <textarea placeholder="Message" asp-for="Message" class="form-control" id="textAreaExample1" rows="10"></textarea>
                            </div>
                            <button type="submit" class="site-btn">Send Message</button>
                        </form>
                        <div asp-validation-summary="ModelOnly" style="color:white"> </div>
                    </div>
                </div>
            </div>
        </div>
    

My Demo Project-1/Views/Home/Index.cshtml
@model List<NewsVM>
@await Component.InvokeAsync("Slider")
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="trending__product">
                    <div class="row">
                        <div class="col-lg-8 col-md-8 col-sm-8">
                            <div class="section-title">
                                <h4>Trending Now</h4>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="btn__all">
                                <a href="#" class="primary-btn">View All <span class="arrow_right"></span></a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        @foreach (var item in Model)
                        {
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="card mb-4 text-white bg-dark">
                                    <a class="img-card" asp-action="index" asp-controller="news" asp-route-title="@Url.FriendlyUrl(item.Title)" asp-route-id="@item.ID">
                                        <img src="~/img/sidebar/@item.ImageURLL" />

                                        <div class="card-content">
                                            <h4 class="card-title">

                                                @item.FrontEndTitle

                                            </h4>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        }

                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-8">
                <div class="product__sidebar">
                    <div class="product__sidebar__view">
                        <div class="section-title">
                            <h5>Top Views</h5>
                        </div>
                       @await Component.InvokeAsync("TopViews")
                    </div>
                    <div class="product__sidebar__comment">
                        <div class="section-title">
                            <h5>New Comment</h5>
                        </div>
                        @await Component.InvokeAsync("LastComments")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>